FROM python:3.10-slim

ARG PIP_PROXY

RUN mkdir -p /opt/dagster/dagster_home

RUN pip install dagster dagster-postgres dagster-webserver

RUN pip install pandas

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

WORKDIR $DAGSTER_HOME
