FROM python:3.10-slim

ARG PIP_PROXY

RUN mkdir -p /opt/dagster/dagster_home

RUN pip install dagster dagster-postgres dagster-webserver

RUN pip install pandas

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY dagster.yaml workspace.yaml $DAGSTER_HOME

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY ./blob_storage/ $DAGSTER_HOME/blob_storage

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY ./blob_storage_tests/ $DAGSTER_HOME/blob_storage_tests

WORKDIR $DAGSTER_HOME
