FROM python:3.10-slim

ARG PIP_PROXY

RUN pip install dagster dagster-postgres dagster-webserver

RUN pip install pandas dagster_aws

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

# Copy dagster instance YAML to /opt/dagster/dagster_home/
COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
