FROM python:3.10-slim

ARG PIP_PROXY

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

ENV DAGSTER_MODULE_NAME=blob_storage

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres

RUN pip install pandas

# Add repository code
RUN mkdir -p $DAGSTER_HOME

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY dagster.yaml workspace.yaml $DAGSTER_HOME

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY ./$DAGSTER_MODULE_NAME/ $DAGSTER_HOME/$DAGSTER_MODULE_NAME

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY ./$DAGSTER_MODULE_NAME_tests/ $DAGSTER_HOME/$DAGSTER_MODULE_NAME

# Run dagster gRPC server on port 4000
EXPOSE 4000

WORKDIR $DAGSTER_HOME
